name: Go App Scheduled Run

on:
  schedule:
    - cron: '0 */12 * * *'  # This schedules the job to run every 12 hours
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  run-go-script:
    runs-on: ubuntu-latest  # Specifies the runner

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Checks out your repository

      - name: Set up Go
        uses: actions/setup-go@v4  # Sets up Go environment
        with:
          go-version: '1.19.1'  # Specifies the Go version

      - name: Run the Go script
        run: go run main.go ping "triggered by GitHub Action"  # Runs your Go program
