name: Go App Scheduled Run

on:
  schedule:
    - cron: '* * * * *'

jobs:
  run-go-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.1'  # Use the latest stable version of Go

      - name: Run the Go script
        run: go run main.go ping "triggered by GitHub Action"
